services:
  - type: web
    name: backend
    runtime: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      chmod -R 775 storage bootstrap/cache
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    env: php