name: Build, push Docker image and run migrations

on:
  push:
    branches:
      - main  # O reemplaza por la rama que usas

jobs:
  build-and-migrate:
    runs-on: ubuntu-latest

    env:
      APP_KEY: ${{ secrets.APP_KEY }}
      APP_ENV: production
      DB_CONNECTION: pgsql
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: 5432
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: humbertojulieta/laravel:latest

    # Paso adicional para correr migraciones
    - name: Run Laravel migrations
      run: |
        sleep 10  # Espera 10 segundos para asegurar que la base de datos está lista
        docker run --rm \
          -e APP_KEY \
          -e APP_ENV \
          -e DB_CONNECTION \
          -e DB_HOST \
          -e DB_PORT \
          -e DB_DATABASE \
          -e DB_USERNAME \
          -e DB_PASSWORD \
          humbertojulieta/laravel:latest \
          php artisan migrate --force
